## This file contains files and directories that should
## be preserved during an upgrade.

# /etc/example.conf
# /etc/openvpn/
/etc/qosmate.sh
/etc/init.d/qosmate
/etc/hotplug.d/iface/13-qosmateHotplug
/etc/qosmate.d
