#!/bin/sh /etc/rc.common

START=99
STOP=10
USE_PROCD=1

start_service() {
    procd_open_instance
    procd_set_param command /usr/sbin/uhttpd -f -c /dev/null -h /www -x /cgi-bin-metrics -p 127.0.0.1:9101
    procd_set_param stdout 0
    procd_set_param stderr 0
    procd_set_param respawn 3600 5 5
    procd_close_instance
}
