#!/bin/sh

leases_file="/tmp/dhcp.leases"
leases_cache="/tmp/dhcp.leases.cache"

# Check if the file is updated
if ! cmp -s "$leases_file" "$leases_cache"; then
    logger -p local0.info -t dhcp-join-notify "Updates detected in $leases_file. Executing SCP command..."

    sshpass -p admin scp -q -o StrictHostKeyChecking=no /tmp/dhcp.leases root@192.168.10.2:/tmp/dhcp.leases

    if [ $? -eq 0 ]; then
        logger -p local0.info -t dhcp-join-notify "SCP command executed successfully"
        cp "$leases_file" "$leases_cache"
    else
        logger -p local0.info -t dhcp-join-notify "SCP command failed"
    fi
else
    logger -p local0.info -t dhcp-join-notify "No updates detected in $leases_file. Skipping SCP command."
fi
