#!/bin/sh
# Restore user-installed packages after firmware upgrade + backup restore
# Uses the package list generated by /etc/script/packages.sh
# Usage: /etc/script/restore-packages.sh

PKG_LIST="/etc/config/my_installed_packages"
LOG="/tmp/restore-packages.log"

if [ ! -f "$PKG_LIST" ]; then
    echo "ERROR: $PKG_LIST not found."
    echo "Run /etc/script/packages.sh first to generate the list."
    exit 1
fi

TOTAL=$(wc -l < "$PKG_LIST")
echo "=== Package Restore - $(date) ===" | tee $LOG
echo "Packages to restore: $TOTAL" | tee -a $LOG
echo "Updating package feeds..." | tee -a $LOG
opkg update >> $LOG 2>&1

if [ $? -ne 0 ]; then
    echo "ERROR: opkg update failed. Check internet connection." | tee -a $LOG
    exit 1
fi

INSTALLED=0
SKIPPED=0
FAILED=0
FAILED_LIST=""

while read -r pkg; do
    [ -z "$pkg" ] && continue
    if opkg status "$pkg" 2>/dev/null | grep -q "^Status.*installed"; then
        SKIPPED=$((SKIPPED + 1))
        continue
    fi
    echo -n "Installing $pkg... " | tee -a $LOG
    opkg install "$pkg" >> $LOG 2>&1
    if [ $? -eq 0 ]; then
        echo "OK" | tee -a $LOG
        INSTALLED=$((INSTALLED + 1))
    else
        echo "FAILED" | tee -a $LOG
        FAILED=$((FAILED + 1))
        FAILED_LIST="$FAILED_LIST $pkg"
    fi
done < "$PKG_LIST"

echo "" | tee -a $LOG
echo "=== Summary ===" | tee -a $LOG
echo "Already installed (skipped): $SKIPPED" | tee -a $LOG
echo "Newly installed: $INSTALLED" | tee -a $LOG
echo "Failed: $FAILED" | tee -a $LOG
[ -n "$FAILED_LIST" ] && echo "Failed packages:$FAILED_LIST" | tee -a $LOG
echo "Log: $LOG" | tee -a $LOG

# Reload kernel params after kmod packages
sysctl -p /etc/sysctl.conf 2>/dev/null
echo "sysctl reloaded." | tee -a $LOG
