#!/bin/sh
chmod +x /usr/bin/linkmonitor-daemon 2>/dev/null
chmod +x /usr/libexec/rpcd/linkmonitor 2>/dev/null
chmod +x /etc/init.d/linkmonitor 2>/dev/null
mkdir -p /tmp/linkmonitor
/etc/init.d/rpcd reload 2>/dev/null
/etc/init.d/linkmonitor enable 2>/dev/null
/etc/init.d/linkmonitor start 2>/dev/null
exit 0
