[routers]
flint2  ansible_host=192.168.10.1
beryl   ansible_host=192.168.10.2

[routers:vars]
ansible_user=root
ansible_ssh_private_key_file=~/.ssh/id_ed25519
ansible_shell_type=sh
# OpenWrt no tiene Python por defecto — usamos raw/command sin gather_facts
ansible_python_interpreter=/usr/bin/python3

[beryl:vars]
# Beryl solo es accesible via ProxyJump desde Flint-2
ansible_ssh_common_args='-o ProxyJump=root@192.168.10.1'
