#!/bin/sh /etc/rc.common
# Link Monitor init script (procd)

START=95
STOP=10
USE_PROCD=1

PROG=/usr/bin/linkmonitor-daemon

start_service() {
	local enabled
	config_load linkmonitor
	config_get enabled global enabled 1

	[ "$enabled" = "1" ] || return 0

	procd_open_instance
	procd_set_param command "$PROG"
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 0
	procd_set_param stderr 1
	procd_set_param pidfile /var/run/linkmonitor.pid
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger "linkmonitor"
}

reload_service() {
	stop
	start
}
